/**
 * Capability reporting for the ForeScene Agent API.
 */

import type { AgentControlMode, ForeSceneAgentCapabilities } from './protocol';
import { FORESCENE_AGENT_API_VERSION } from './protocol';
import { getForeSceneRuntimeServices } from './runtimeRegistry';

/** Inspection commands available in PR1. */
export const AGENT_INSPECT_COMMANDS = [
  'app.status',
  'app.capabilities',
  'project.inspect',
  'project.document',
  'asset.missing.list',
  'shot.document',
  'object.list',
  'object.find',
  'object.inspect',
  'shot.list',
  'shot.inspect',
  'shot.timeline.inspect',
  'shot.timeline.sample',
  'shot.state.sample',
  'shot.diagnostics.inspect',
  'artifact.download',
  'agent.describeCapabilities',
  'agent.describeOperation',
  'agent.schema',
  'landmark.list',
  'export.plan',
  'viewport.waitReady',
  'shot.renderFrame',
  'character.analyze',
  'character.analyzeSavedRig',
  'character.progress',
  'project.loadedSource',
  'objectGroup.list',
  'objectGroup.inspect',
  'shot.listMedia',
  'shot.compareAdjacent',
  'sequence.continuity',
  'pose.inspect',
  'revision.list',
  'project.health',
  'project.storage',
  'artifact.list',
  'artifact.status',
  'production.status',
  'production.configuration.inspect',
  'production.configuration.validate',
  'production.capabilities.inspect',
  'production.capabilities.validate',
  'production.pose.resolve',
  'production.shotEnvironment.inspect',
  'production.shotEnvironment.verifyPanorama',
  'production.projectionHealth.inspect',
  'production.shotPresence.inspect',
  'production.shotPresence.verify',
  'production.shotComposition.inspect',
  'production.shotComposition.verify',
  'production.canary.inspect',
  'production.stillLayout.inspect',
  'production.reviewSamples.plan',
  'production.reviewArtifacts.plan',
  'production.renderCache.inspect',
  'production.renderCache.explain',
  'production.run.get',
  'production.run.list',
] as const;

/** Mutation / plan commands available when write access is enabled. */
export const AGENT_MUTATE_COMMANDS = [
  'project.updateInfo',
  'object.create',
  'object.update',
  'object.transform.set',
  'object.duplicate',
  'object.delete',
  'object.setVisible',
  'object.setLocked',
  'selection.setObjects',
  'workspace.open',
  'shot.create',
  'shot.rename',
  'shot.updateDescription',
  'shot.camera.set',
  'shot.panorama.set',
  'shot.select',
  'shot.copyStagingToNext',
  'shot.stageObject',
  'shot.clearObjectPose',
  'shot.clearObjectStaging',
  'shot.timeline.replace',
  'shot.timeline.clear',
  'shot.timeline.setDuration',
  'shot.keyframe.create',
  'shot.keyframe.update',
  'shot.keyframe.delete',
  'shot.keyframe.stageObject',
  'shot.keyframe.clearStaging',
  'shot.delete',
  'landmark.create',
  'landmark.update',
  'landmark.delete',
  'landmark.linkObject',
  'export.sceneDefaults.patch',
  'export.shotOverrides.patch',
  'export.shotOverrides.reset',
  'export.shotOverrides.copy',
  'export.shotOverrides.promote',
  'export.package',
  'project.backup.export',
  'project.reset',
  'spatial.snapToFloor',
  'spatial.placeNearLandmark',
  'spatial.frameSubjects',
  'spatial.orientToward',
  'spatial.trackSubjects',
  'shot.keyframe.captureState',
  'shot.keyframe.upsertObject',
  'revision.refresh',
  'production.renderCache.invalidate',
  'production.renderCache.clear',
  'character.import',
  'character.importSavedRig',
  'model.import',
  'asset.relink',
  'asset.missing.remove',
  'project.openPackage',
  'project.validatePackage',
  'project.cloneRevision',
  'pano.import',
  'pano.update',
  'pano.renderGraybox',
  'pano.approve',
  'pano.acceptAlignment',
  'pano.remove',
  'pano.setCaptureOrigin',
  'setBlueprint.apply',
  'setBlueprint.validate',
  'project.settings.patch',
  'objectGroup.create',
  'objectGroup.stage',
  'job.submit',
  'job.cancel',
  'job.resume',
  'shot.duplicate',
  'shot.reorder',
  'shot.captureThumbnail',
  'pose.setJoint',
  'pose.applyPreset',
  'pose.mirror',
  'pose.resetJoint',
  'pose.copyBetweenShots',
  'rig.export',
  'revision.restore',
  'revision.compare',
  'project.cleanupAssets',
  'project.repair',
  'artifact.persist',
  'artifact.delete',
  'production.apply',
  'production.entity.bind',
  'production.location.define',
  'production.binding.remove',
  'production.poseSubstitution.approve',
  'production.verifiedReplacement.apply',
  'production.shotPresence.set',
  'production.shotPresence.repair',
  'production.shotComposition.set',
  'production.shotComposition.solve',
  'production.canary.plan',
  'production.canary.run',
  'production.canary.approve',
  'production.stillLayout.approve',
  'production.motionRevision.create',
  'production.run.start',
  'production.run.pause',
  'production.run.resume',
  'production.run.cancel',
  'batch.inspectDiagnostics',
  'batch.frameSubjects',
  'batch.renderShots',
  'batch.renderPassMatrix',
  'batch.contactSheets',
] as const;

export const AGENT_DEFERRED_COMMANDS = [
  'character.cancel',
] as const;

export const AGENT_RUNTIME_COMMANDS = [
  'viewport.waitReady',
  'shot.renderFrame',
  'viewport.capture',
] as const;

export function buildAgentCapabilities(
  controlMode: AgentControlMode,
): ForeSceneAgentCapabilities {
  const runtime = getForeSceneRuntimeServices();
  const writeAccess = controlMode === 'read-write';
  return {
    apiVersion: FORESCENE_AGENT_API_VERSION,
    controlMode,
    inspection: controlMode !== 'off',
    mutations: writeAccess,
    packageExport: true,
    characterImport: true,
    projectReplacement: writeAccess,
    missingAssetRecovery: writeAccess,
    timelineInspection: controlMode !== 'off',
    timelineSampling: controlMode !== 'off',
    commands: {
      inspect: [...AGENT_INSPECT_COMMANDS],
      mutate: [...AGENT_MUTATE_COMMANDS],
      deferred: [...AGENT_DEFERRED_COMMANDS],
    },
    runtime: {
      focusObjects: typeof runtime.focusObjects === 'function',
      focusShot: typeof runtime.focusShot === 'function',
      captureViewport: typeof runtime.captureViewport === 'function',
      renderShotFrame: true,
      waitForViewportReady: true,
    },
  };
}
