/**
 * Machine-readable discovery for the ForeScene Agent API.
 */

import type { AgentControlMode } from './protocol';
import { FORESCENE_AGENT_API_VERSION } from './protocol';
import {
  AGENT_DEFERRED_COMMANDS,
  AGENT_INSPECT_COMMANDS,
  AGENT_MUTATE_COMMANDS,
  buildAgentCapabilities,
} from './capabilities';
import { AGENT_EXECUTABLE_OPS, AGENT_PLAN_LIMITS } from './constants';
import type {
  AgentOperationDescription,
  AgentSchemaDocument,
} from './protocol';

const OPERATION_DOCS: Record<string, AgentOperationDescription> = {
  setShotPanorama: {
    name: 'setShotPanorama',
    category: 'mutation',
    summary: 'Atomically set or clear a shot linked panorama and pano crop.',
    writeAccess: true,
    input: {
      shotId: 'string',
      panoId: 'string | null',
    },
    returns: 'AgentShotPanoramaResult',
  },
  downloadArtifact: {
    name: 'downloadArtifact',
    category: 'inspect',
    summary: 'Retrieve a previously registered render or export artifact by handle.',
    writeAccess: false,
    input: {
      artifactId: 'string',
      download: 'boolean (optional, default true)',
    },
    returns: 'AgentArtifactDownloadResult',
  },
  exportProjectBackup: {
    name: 'exportProjectBackup',
    category: 'mutation',
    summary: 'Build a verified portable project backup and return an artifact handle.',
    writeAccess: true,
    input: {
      download: 'boolean (optional, default false)',
    },
    returns: 'AgentProjectBackupResult',
  },
  inspectShotDiagnostics: {
    name: 'inspectShotDiagnostics',
    category: 'inspect',
    summary: 'Deterministic shot visibility, grounding, occlusion, and motion diagnostics.',
    writeAccess: false,
    input: {
      shotId: 'string',
      timeSeconds: 'number (optional)',
      subjectIds: 'string[] (optional — inspect any renderable object by id)',
    },
    returns: 'AgentShotDiagnostics',
  },
  snapObjectToFloor: {
    name: 'snapObjectToFloor',
    category: 'mutation',
    summary: 'Ground an upright object on the identified floor for one shot via objectOverrides.',
    writeAccess: true,
    input: { shotId: 'string', object: 'AgentEntityTarget' },
    returns: 'AgentSnapObjectToFloorResult',
  },
  placeObjectNearLandmark: {
    name: 'placeObjectNearLandmark',
    category: 'mutation',
    summary: 'Place an object relative to a landmark for one shot via objectOverrides.',
    writeAccess: true,
    input: {
      shotId: 'string',
      object: 'AgentEntityTarget',
      landmark: 'AgentEntityTarget',
      offset: '[x, y, z] (optional)',
    },
    returns: 'AgentPlaceObjectNearLandmarkResult',
  },
  frameSubjects: {
    name: 'frameSubjects',
    category: 'mutation',
    summary: 'Solve and apply a semantic camera framing for one or more subjects.',
    writeAccess: true,
    input: {
      shotId: 'string',
      subjectIds: 'string[]',
      composition: 'string (optional)',
      shotSize: 'string (optional)',
      padding: 'number (optional)',
    },
    returns: 'AgentFrameSubjectsResult',
  },
  orientObjectToward: {
    name: 'orientObjectToward',
    category: 'mutation',
    summary: 'Rotate an object to face another object for one shot via objectOverrides.',
    writeAccess: true,
    input: { shotId: 'string', object: 'AgentEntityTarget', target: 'AgentEntityTarget' },
    returns: 'AgentOrientObjectTowardResult',
  },
  trackSubjects: {
    name: 'trackSubjects',
    category: 'mutation',
    summary: 'Create start/end keyframes that frame subjects at their timeline positions.',
    writeAccess: true,
    input: {
      shotId: 'string',
      subjectIds: 'string[]',
      startTime: 'number (optional)',
      endTime: 'number (optional)',
      composition: 'string (optional)',
    },
    returns: 'AgentTrackSubjectsResult',
  },
  captureShotStateAsKeyframe: {
    name: 'captureShotStateAsKeyframe',
    category: 'mutation',
    summary: 'Capture the current shot staging as an explicit keyframe.',
    writeAccess: true,
    input: { shotId: 'string', timeSeconds: 'number' },
    returns: 'AgentCaptureKeyframeResult',
  },
  sampleShotState: {
    name: 'sampleShotState',
    category: 'inspect',
    summary: 'Sample camera and object overrides at a timeline time.',
    writeAccess: false,
    input: { shotId: 'string', timeSeconds: 'number' },
    returns: 'AgentShotTimeSample',
  },
  upsertObjectKeyframe: {
    name: 'upsertObjectKeyframe',
    category: 'mutation',
    summary: 'Create or update an object override at a timeline time.',
    writeAccess: true,
    input: {
      shotId: 'string',
      objectId: 'string',
      timeSeconds: 'number',
      preserveExplicitState: 'boolean (optional)',
    },
    returns: 'AgentUpsertObjectKeyframeResult',
  },
  describeCapabilities: {
    name: 'describeCapabilities',
    category: 'inspect',
    summary: 'Return machine-readable capability metadata and command catalog.',
    writeAccess: false,
    returns: 'AgentCapabilityDescription',
  },
  describeOperation: {
    name: 'describeOperation',
    category: 'inspect',
    summary: 'Return documentation for a single Agent API operation.',
    writeAccess: false,
    input: { operation: 'string' },
    returns: 'AgentOperationDescription',
  },
  getAgentSchema: {
    name: 'getAgentSchema',
    category: 'inspect',
    summary: 'Return a JSON-schema-like document for plan and result types.',
    writeAccess: false,
    returns: 'AgentSchemaDocument',
  },
  refreshRevision: {
    name: 'refreshRevision',
    category: 'mutation',
    summary: 'Flush persistence and return the latest verified revision id.',
    writeAccess: true,
    returns: 'AgentRevisionRefreshResult',
  },
  inspectProductionConfiguration: {
    name: 'inspectProductionConfiguration',
    category: 'inspect',
    summary: 'Inspect typed prepared production bindings, locations, and contract counts.',
    writeAccess: false,
    returns: 'AgentProductionConfigurationInspection',
  },
  validateProductionConfiguration: {
    name: 'validateProductionConfiguration',
    category: 'inspect',
    summary: 'Validate a production manifest against persisted bindings and prepared location contracts.',
    writeAccess: false,
    input: { manifest: 'unknown' },
    returns: 'AgentProductionConfigurationValidationResult',
  },
  bindProductionEntity: {
    name: 'bindProductionEntity',
    category: 'mutation',
    summary: 'Persist a typed object, group, location, or panorama binding for a production entity.',
    writeAccess: true,
    input: { entityId: 'string', binding: 'ProductionEntityBinding' },
    returns: 'AgentProductionConfigurationMutationResult',
  },
  defineProductionLocation: {
    name: 'defineProductionLocation',
    category: 'mutation',
    summary: 'Persist reusable location geometry, anchors, blockers, zones, and panorama references.',
    writeAccess: true,
    input: { location: 'ProductionLocationDefinition' },
    returns: 'AgentProductionConfigurationMutationResult',
  },
  removeProductionBinding: {
    name: 'removeProductionBinding',
    category: 'mutation',
    summary: 'Remove a prepared production entity binding while preserving other contracts.',
    writeAccess: true,
    input: { entityId: 'string' },
    returns: 'AgentProductionConfigurationMutationResult',
  },
  inspectEntityCapability: {
    name: 'inspectEntityCapability',
    category: 'inspect',
    summary: 'Inspect render, assembly, pose, deformation, and rig-readiness capabilities for a prepared entity.',
    writeAccess: false,
    input: { entityId: 'string' },
    returns: 'AgentEntityCapabilityProfile',
  },
  validateProductionCapabilities: {
    name: 'validateProductionCapabilities',
    category: 'inspect',
    summary: 'Validate every persisted or manifest-inferred capability requirement before production compilation.',
    writeAccess: false,
    input: { manifest: 'unknown (optional)' },
    returns: 'AgentProductionCapabilitiesValidationResult',
  },
  resolveProductionPose: {
    name: 'resolveProductionPose',
    category: 'inspect',
    summary: 'Resolve a requested semantic pose as exact, approved, approximate, or contradictory.',
    writeAccess: false,
    input: { entityId: 'string', requestedPose: 'string', shotId: 'string (optional)' },
    returns: 'AgentProductionPoseResolution',
  },
  approvePoseSubstitution: {
    name: 'approvePoseSubstitution',
    category: 'mutation',
    summary: 'Persist an explicit project-approved semantic pose substitution for production reports and compilation.',
    writeAccess: true,
    input: { approval: 'PoseSubstitutionApproval' },
    returns: 'AgentPoseSubstitutionMutationResult',
  },
  applyVerifiedProxyReplacement: {
    name: 'applyVerifiedProxyReplacement',
    category: 'mutation',
    summary: 'Apply a proxy replacement only after postcondition verification, rolling back a failed replacement automatically.',
    writeAccess: true,
    input: { proxyObjectId: 'string', replacementObjectId: 'string', requestedShotIds: 'string[] (optional)' },
    returns: 'AgentVerifiedProxyReplacementResult',
  },
  setShotPresenceContract: {
    name: 'setShotPresenceContract',
    category: 'mutation',
    summary: 'Persist the exact dynamic object and logical group visibility contract for a shot.',
    writeAccess: true,
    input: { shotId: 'string', contract: 'ShotPresenceContract' },
    returns: 'AgentShotPresenceMutationResult',
  },
  inspectShotPresence: {
    name: 'inspectShotPresence',
    category: 'inspect',
    summary: 'Inspect closed-world dynamic presence for the shot and sampled timeline states.',
    writeAccess: false,
    input: { shotId: 'string' },
    returns: 'AgentShotPresenceInspection',
  },
  verifyShotPresence: {
    name: 'verifyShotPresence',
    category: 'inspect',
    summary: 'Verify a shot against its exact dynamic presence contract.',
    writeAccess: false,
    input: { shotId: 'string' },
    returns: 'AgentShotPresenceInspection',
  },
  repairShotPresence: {
    name: 'repairShotPresence',
    category: 'mutation',
    summary: 'Repair shot and timeline visibility to the closed-world contract without changing the camera.',
    writeAccess: true,
    input: { shotId: 'string' },
    returns: 'AgentShotPresenceMutationResult',
  },
  inspectShotEnvironmentContract: {
    name: 'inspectShotEnvironmentContract',
    category: 'inspect',
    summary: 'Inspect the prepared location and expected panorama contract for a shot.',
    writeAccess: false,
    input: { shotId: 'string' },
    returns: 'AgentShotEnvironmentInspection',
  },
  verifyShotPanorama: {
    name: 'verifyShotPanorama',
    category: 'inspect',
    summary: 'Verify that a shot links the panorama required by its prepared environment contract.',
    writeAccess: false,
    input: { shotId: 'string' },
    returns: 'AgentShotEnvironmentInspection',
  },
  inspectProjectionHealth: {
    name: 'inspectProjectionHealth',
    category: 'inspect',
    summary: 'Render a projected coverage debug pass and gate panorama contribution using renderer-derived metrics.',
    writeAccess: false,
    input: { shotId: 'string', timeSeconds: 'number (optional)', minimumCoverage: 'number (optional)' },
    returns: 'AgentProjectionHealthInspection',
  },
  setShotCompositionConstraints: {
    name: 'setShotCompositionConstraints',
    category: 'mutation',
    summary: 'Persist normalized storyboard or layout constraints for a shot.',
    writeAccess: true,
    input: { shotId: 'string', contract: 'ShotCompositionConstraintSet' },
    returns: 'AgentShotCompositionMutationResult',
  },
  inspectShotCompositionError: {
    name: 'inspectShotCompositionError',
    category: 'inspect',
    summary: 'Measure a shot against its reference-driven screen-space composition contract.',
    writeAccess: false,
    input: { shotId: 'string' },
    returns: 'AgentShotCompositionInspection',
  },
  solveShotToCompositionConstraints: {
    name: 'solveShotToCompositionConstraints',
    category: 'mutation',
    summary: 'Refine camera position, target, and FOV toward a saved composition contract.',
    writeAccess: true,
    input: { shotId: 'string', maxIterations: 'number (optional)' },
    returns: 'AgentShotCompositionMutationResult',
  },
  verifyShotCompositionConstraints: {
    name: 'verifyShotCompositionConstraints',
    category: 'inspect',
    summary: 'Run the hard composition-contract verifier for a shot.',
    writeAccess: false,
    input: { shotId: 'string' },
    returns: 'AgentShotCompositionInspection',
  },
  planProductionCanary: {
    name: 'planProductionCanary',
    category: 'inspect',
    summary: 'Select the smallest deterministic canary covering the production high-risk capabilities.',
    writeAccess: false,
    input: { manifest: 'unknown', maxShots: 'number (optional)' },
    returns: 'AgentProductionCanaryPlanResult',
  },
  runProductionCanary: {
    name: 'runProductionCanary',
    category: 'mutation',
    summary: 'Record and gate the observed canary state and review outputs.',
    writeAccess: true,
    input: { runId: 'string', results: 'ProductionCanaryShotResult[]' },
    returns: 'AgentProductionCanaryRunResult',
  },
  approveProductionCanary: {
    name: 'approveProductionCanary',
    category: 'mutation',
    summary: 'Approve a passing canary or record an explicit override reason.',
    writeAccess: true,
    input: { runId: 'string', overrideReason: 'string (optional)' },
    returns: 'AgentProductionCanaryApprovalResult',
  },
  inspectProductionGates: {
    name: 'inspectProductionGates',
    category: 'inspect',
    summary: 'Inspect persisted production gate state and full-run lock status.',
    writeAccess: false,
    input: { runId: 'string (optional)' },
    returns: 'ProductionGateState',
  },
  approveStillLayout: {
    name: 'approveStillLayout',
    category: 'mutation',
    summary: 'Create an immutable approved still-layout revision after full still verification.',
    writeAccess: true,
    input: { runId: 'string', approvedShotIds: 'string[]', reviewArtifactIds: 'string[] (optional)', reviewRecord: 'string (optional)' },
    returns: 'AgentStillLayoutApprovalResult',
  },
  createMotionWorkingRevision: {
    name: 'createMotionWorkingRevision',
    category: 'mutation',
    summary: 'Clone the approved still-layout revision into a separate motion working revision.',
    writeAccess: true,
    input: { runId: 'string' },
    returns: 'AgentMotionWorkingRevisionResult',
  },
  inspectStillLayoutApproval: {
    name: 'inspectStillLayoutApproval',
    category: 'inspect',
    summary: 'Inspect the immutable still-layout approval and motion-branch reference.',
    writeAccess: false,
    input: { runId: 'string (optional)' },
    returns: 'AgentStillLayoutApprovalResult',
  },
  planReviewSamples: {
    name: 'planReviewSamples',
    category: 'inspect',
    summary: 'Plan the minimum event-aware review samples for a static or motion shot.',
    writeAccess: false,
    input: { shotId: 'string', strategy: 'event-aware | single (optional)', maxSamples: 'number (optional)' },
    returns: 'ReviewSamplePlan',
  },
  planProductionReviewArtifacts: {
    name: 'planProductionReviewArtifacts',
    category: 'inspect',
    summary: 'Group canonical review frames into master, location, motion, and continuity artifacts.',
    writeAccess: false,
    input: { frames: 'ProductionReviewFrameInput[]', continuityStripSize: 'number (optional)' },
    returns: 'ProductionReviewArtifactPlanResult',
  },
  inspectRenderCache: {
    name: 'inspectRenderCache',
    category: 'inspect',
    summary: 'Inspect cached production frames and their dependency fingerprints.',
    writeAccess: false,
    input: { projectId: 'string (optional)' },
    returns: 'RenderCacheInspection',
  },
  explainRenderCacheHit: {
    name: 'explainRenderCacheHit',
    category: 'inspect',
    summary: 'Explain whether a render fingerprint can reuse a cached artifact.',
    writeAccess: false,
    input: { projectId: 'string (optional)', fingerprint: 'RenderFingerprint' },
    returns: 'RenderCacheDecision',
  },
  explainRenderCacheMiss: {
    name: 'explainRenderCacheMiss',
    category: 'inspect',
    summary: 'Explain why a render fingerprint cannot reuse a cached artifact.',
    writeAccess: false,
    input: { projectId: 'string (optional)', fingerprint: 'RenderFingerprint' },
    returns: 'RenderCacheDecision',
  },
  invalidateRenderDependencies: {
    name: 'invalidateRenderDependencies',
    category: 'mutation',
    summary: 'Invalidate cached frames that depend on changed project entities.',
    writeAccess: true,
    input: { projectId: 'string (optional)', dependencyIds: 'string[]' },
    returns: 'RenderCacheInspection',
  },
  clearRenderCache: {
    name: 'clearRenderCache',
    category: 'mutation',
    summary: 'Clear cached render artifacts without changing the project.',
    writeAccess: true,
    input: { projectId: 'string (optional)' },
    returns: 'RenderCacheInspection',
  },
  runProduction: {
    name: 'runProduction',
    category: 'mutation',
    summary: 'Start a persisted browser-owned production run and its capability canary gate.',
    writeAccess: true,
    input: { manifest: 'unknown', maxCanaryShots: 'number (optional)' },
    returns: 'AgentProductionRunResult',
  },
  getProductionRun: {
    name: 'getProductionRun',
    category: 'inspect',
    summary: 'Read one persisted production run including gate, cache, and artifact state.',
    writeAccess: false,
    input: { runId: 'string' },
    returns: 'AgentProductionRunState | undefined',
  },
  listProductionRuns: {
    name: 'listProductionRuns',
    category: 'inspect',
    summary: 'List persisted production runs for restart and review recovery.',
    writeAccess: false,
    input: {},
    returns: 'AgentProductionRunState[]',
  },
  pauseProductionRun: {
    name: 'pauseProductionRun',
    category: 'mutation',
    summary: 'Pause a nonterminal production run at its current gate.',
    writeAccess: true,
    input: { runId: 'string' },
    returns: 'AgentProductionRunResult',
  },
  resumeProductionRun: {
    name: 'resumeProductionRun',
    category: 'mutation',
    summary: 'Resume a run after its blocking canary or still-layout approval.',
    writeAccess: true,
    input: { runId: 'string' },
    returns: 'AgentProductionRunResult',
  },
  cancelProductionRun: {
    name: 'cancelProductionRun',
    category: 'mutation',
    summary: 'Cancel a nonterminal production run while preserving completed artifacts.',
    writeAccess: true,
    input: { runId: 'string' },
    returns: 'AgentProductionRunResult',
  },
};

export function describeAgentCapabilities(controlMode: AgentControlMode) {
  const capabilities = buildAgentCapabilities(controlMode);
  return {
    apiVersion: FORESCENE_AGENT_API_VERSION,
    controlMode,
    capabilities,
    operations: Object.keys(OPERATION_DOCS),
    commands: {
      inspect: [...AGENT_INSPECT_COMMANDS],
      mutate: [...AGENT_MUTATE_COMMANDS],
      deferred: [...AGENT_DEFERRED_COMMANDS],
    },
    renderResultContract: {
      status: ['completed', 'completed_with_warnings', 'failed', 'stale_revision', 'cancelled', 'busy'],
      artifactKinds: ['inline', 'handle'],
      okSemantics: 'ok is true when status is completed or completed_with_warnings',
    },
    revisionContract: {
      everyMutationReturnsRevisionId: true,
      staleRecovery: 'call refreshRevision() then retry, or use automatic render retry',
    },
  };
}

export function describeAgentOperation(operation: string): AgentOperationDescription | undefined {
  return OPERATION_DOCS[operation];
}

export function getAgentSchema(): AgentSchemaDocument {
  return {
    apiVersion: FORESCENE_AGENT_API_VERSION,
    plan: {
      version: 1,
      limits: AGENT_PLAN_LIMITS,
      executableOps: [...AGENT_EXECUTABLE_OPS],
    },
    results: {
      renderShotFrame: {
        status: 'AgentOperationStatus',
        artifact: 'AgentArtifactInline | undefined',
        diagnostics: 'AgentDiagnostic[]',
        legacy: ['ok', 'pngDataUrl', 'pixelStats'],
      },
      renderShotVideo: {
        status: 'AgentOperationStatus',
        artifact: 'AgentArtifactHandle | undefined',
        diagnostics: 'AgentDiagnostic[]',
        legacy: ['ok', 'fileName', 'assetId'],
      },
      exportPackage: {
        status: 'AgentOperationStatus',
        artifact: 'AgentArtifactHandle | undefined',
        diagnostics: 'AgentDiagnostic[]',
      },
      exportProjectBackup: {
        status: 'AgentOperationStatus',
        artifact: 'AgentArtifactHandle',
        diagnostics: 'AgentDiagnostic[]',
      },
    },
    diagnostics: {
      severities: ['info', 'warning', 'error'],
      commonCodes: [
        'write_access_required',
        'stale_revision',
        'target_not_found',
        'frame_zero_variance',
        'artifact_not_found',
      ],
    },
  };
}
