import type { Workspace } from '../../domain/types';

export interface HelpControl {
  label: string;
  description: string;
  details?: readonly string[];
  keywords?: readonly string[];
}

export interface HelpTopic {
  id: string;
  title: string;
  summary: string;
  controls: readonly HelpControl[];
  notes?: readonly string[];
  defaultOpen?: boolean;
}

export interface HelpSection {
  id: string;
  group: 'Start here' | 'Workspaces' | 'Project & guidance' | 'Reference';
  navLabel: string;
  title: string;
  description: string;
  workspace?: Workspace;
  mode?: 'panoViewer';
  topics: readonly HelpTopic[];
}

export const helpSections: readonly HelpSection[] = [
  {
    id: 'getting-started',
    group: 'Start here',
    navLabel: 'Getting started',
    title: 'Getting started',
    description: 'Choose the right mode, understand the four-stage workflow, and learn what ForeScene saves locally.',
    topics: [
      {
        id: 'choose-mode',
        title: 'Intro and mode chooser',
        summary: 'The first-run intro can be skipped, and the mode chooser separates the full ForeScene studio from the lightweight panorama viewer.',
        defaultOpen: true,
        controls: [
          { label: 'Skip intro', description: 'Dismisses the opening video. Clicking the video, pressing Escape, Enter, or Space also dismisses it. The choice is remembered in this browser.' },
          { label: 'Open ForeScene', description: 'Opens the complete Build → Reference → Shots → Export workflow: sets, characters, shots, continuity tools, and export handoffs. When the active project is blank, the first-project launcher appears next.' },
          { label: 'Just view a 360 pano', description: 'Opens the independent panorama viewer. This mode does not modify the current ForeScene project.' },
          { label: 'Switch modes later', description: 'Open the top-left brand menu and choose Simple 360 Viewer or Open ForeScene.' },
        ],
      },
      {
        id: 'first-project-launcher',
        title: 'First project launcher',
        summary: 'After you open ForeScene Studio with a blank project, a production-oriented launcher asks how you want to start so you never land in an unexplained empty Build workspace.',
        defaultOpen: true,
        controls: [
          {
            label: 'Automated Previs (Advanced)',
            description: 'Opens the Agent Console for use with an external coding agent. A guided shot-list wizard is planned; today this is the advanced agent handoff surface.',
          },
          {
            label: 'Build Manually',
            description: 'Create a blank graybox set, open the temple starter courtyard, or import an existing project backup — then build shots yourself.',
          },
          {
            label: 'Featured sample (Dialogue Demo)',
            description: 'Opens the Dialogue Demo: one room, graybox + styled panoramas, two characters, a table prop, four coverage shots with thumbnails, contact sheet, and export settings. Safe to experiment; use Reset sample to restore the baseline.',
          },
          {
            label: 'Open Existing Project',
            description: 'Import a ForeScene backup (.fsp / .zip / .json). Locally recovered projects remain available under Project Safety & Recovery.',
          },
          {
            label: 'Skip to Build',
            description: 'Dismisses the launcher for this blank session and opens Build directly. Advanced users can always skip guidance.',
          },
          {
            label: 'Reset sample',
            description: 'When the Dialogue Demo is open, Project menu → Reset Sample reloads the bundled baseline so experiments stay reversible.',
          },
        ],
        notes: [
          'The launcher only appears when the active project is effectively blank (origin / floor scaffolding only). Real projects and the sample never re-show it unexpectedly.',
          'Recovered local projects open in Studio without the launcher because they are not blank.',
        ],
      },
      {
        id: 'four-stage-workflow',
        title: 'The four-stage workflow',
        summary: 'Each workspace produces the information needed by the next one — from set construction and character staging through shot design and production handoffs.',
        defaultOpen: true,
        controls: [
          { label: 'Build', description: 'Block the set, import geometry and poseable characters, place the panorama capture origin, and render a graybox 360.' },
          { label: 'Reference', description: 'Import, align, approve, and manage the visual panorama references used for projection and shot matching.' },
          { label: 'Shots', description: 'Compose still cameras, author camera moves, stage objects and character poses per shot, and manage the shot sequence.' },
          { label: 'Export', description: 'Select shots and build handoff ZIPs containing the chosen visual references, camera data, media, prompts, and manifest.' },
        ],
        notes: [
          'The stage navigation across the top moves left to right, but you may revisit any completed stage.',
          'The Current Objective guidance explains the next useful action without blocking manual navigation.',
        ],
      },
      {
        id: 'local-first',
        title: 'Local-first projects',
        summary: 'Project documents, recovery revisions, imported media, and generated captures stay in the browser until you explicitly download a file.',
        controls: [
          { label: 'Save status', description: 'The header shows Unsaved changes, Saving locally, Saved locally, Recovered locally, or Local save failed.' },
          { label: 'Verified saves', description: 'Important destructive, rendering, and export operations wait for a verified project revision so recovery remains trustworthy.' },
          { label: 'Project backup', description: 'A portable editable backup. Use this when moving the project to another browser or machine.' },
          { label: 'Handoff ZIP', description: 'A production deliverable created in Export. It is not the editable project file.' },
        ],
      },
    ],
  },
  {
    id: 'app-shell',
    group: 'Start here',
    navLabel: 'App controls',
    title: 'App header, navigation, and project menu',
    description: 'Everything available in the top bar and the ForeScene brand menu.',
    topics: [
      {
        id: 'brand-menu',
        title: 'Top-left brand menu',
        summary: 'Click ForeScene in the upper-left corner to open project actions, mode switching, safety tools, and documentation.',
        controls: [
          { label: 'Project name', description: 'Edits the project display name. The name appears in backups, recovery history, and exported package naming.' },
          { label: 'Current Objective', description: 'Opens contextual guidance for the current workflow stage.' },
          { label: 'Simple 360 Viewer', description: 'Switches to the standalone panorama viewer without changing the continuity project.' },
          { label: 'New Project', description: 'Starts a blank project after confirmation. A local recovery point is retained for the project being replaced.' },
          { label: 'Import Project Backup', description: 'Opens an editable ForeScene backup. Imports are validated before replacing the active project.' },
          { label: 'Project Safety & Recovery', description: 'Opens revision history, storage information, health checks, cleanup, and repair tools.' },
          { label: 'Export Project Backup', description: 'Downloads a verified editable backup, including project state and locally stored media.' },
          { label: 'Package Export', description: 'Navigates directly to the Export workspace.' },
          { label: 'Help & Documentation', description: 'Opens this searchable manual.' },
        ],
      },
      {
        id: 'header-actions',
        title: 'Header actions and stage navigation',
        summary: 'The right side contains fast project actions; the center contains the production stages.',
        controls: [
          { label: 'Import backup icon', description: 'Fast access to Import Project Backup.' },
          { label: 'Export backup icon', description: 'Fast access to Export Project Backup.' },
          { label: 'Theme button', description: 'Switches between light and dark appearance.' },
          { label: 'Build / Reference / Shots / Export', description: 'Navigates among the four production workspaces. On smaller screens these appear in a horizontally scrollable row.' },
          { label: 'Save-status indicator', description: 'Shows local persistence state. Hover or open the brand menu for a longer status message.' },
        ],
      },
    ],
  },
  {
    id: 'build',
    group: 'Workspaces',
    navLabel: 'Build',
    title: 'Build workspace',
    description: 'Create the graybox scene, control object properties, manage the capture origin, and generate panorama references.',
    workspace: 'build',
    topics: [
      {
        id: 'build-viewport',
        title: 'Viewport and camera navigation',
        summary: 'Use orbit/select navigation for editing or switch to a first-person free camera for evaluating movement and clearance.',
        defaultOpen: true,
        controls: [
          { label: 'Orbit/select mode', description: 'Drag to orbit the scene while retaining normal object selection and gizmo editing.' },
          { label: 'Free camera', description: 'Drag to look and use WASD to move. Space and Shift move vertically, double-tap W to sprint, and Escape exits. Phones use the on-screen movement pad and Up/Dn controls.' },
          { label: 'Frame selection / Frame all', description: 'F frames selected objects; Home frames all visible objects.' },
          { label: 'Scene guides', description: 'Shows or hides helpers and camera frustums. Guides are not included in rendered deliverables.' },
          { label: 'Visibility distance', description: 'Adjusts the Build viewport draw distance and fog/shroud cutoff. It does not change shot or export cameras.' },
        ],
      },
      {
        id: 'build-object-tray',
        title: 'Object tray and placement',
        summary: 'Select a primitive and click the floor to stamp it into the graybox.',
        controls: [
          { label: 'Select', description: 'Returns to selection mode. V or Escape also returns to selection.' },
          { label: 'Origin', description: 'Edits the panorama capture origin instead of scene objects.' },
          { label: 'Snap', description: 'Turns grid snapping on or off for placement and transforms.' },
          { label: 'Primitive buttons', description: 'Box, Floor, Wall, Doorway, Tree, Column, Stairs, Sun, Arch, Terrain, Backdrop, and Person create the corresponding graybox object.' },
          { label: 'Number keys 1–9 / 0', description: 'Quickly chooses the most common primitive tools.' },
          { label: 'More', description: 'Reveals less-frequent primitive types, Generate set from description, and the 3D scene importer.' },
          { label: 'Generate set from description', description: 'Opens the SetBlueprint workflow: describe a set, paste validated JSON from an external model, review spatial blocking, and replace the project safely.' },
          { label: 'Import 3D model or scene', description: 'Opens the geometry-only import workflow described below.' },
          { label: 'Import poseable character', description: 'Opens the separate poseable-character wizard for upright humanoid GLB, embedded glTF, or FBX. Existing skeletons and skin weights can be preserved, or the mesh can use the ForeScene autorig path.' },
        ],
      },
      {
        id: 'build-set-generation',
        title: 'Generate set from description',
        summary: 'Create a graybox set from a spatial description or pasted SetBlueprint JSON. AI output is never trusted until it passes local validation.',
        controls: [
          { label: 'Describe tab', description: 'Enter a set description plus optional width, depth, detail level, and constraints. Copy the shared system prompt for an external model when no generation endpoint is configured.' },
          { label: 'Paste blueprint JSON', description: 'Paste SetBlueprint JSON from any frontier model or coding agent. Markdown fences and surrounding prose are stripped, then validated.' },
          { label: 'Copy prompt for external model', description: 'Copies the authoritative system prompt and a user prompt built from your description fields.' },
          { label: 'Validate and review', description: 'Parses the JSON, reports field-level diagnostics, compiles a preview, and shows object counts, bounds, landmarks, assumptions, and warnings.' },
          { label: 'Object search', description: 'Filters the review object list by name, key, or primitive type.' },
          { label: 'Show raw JSON', description: 'Optional drawer for inspecting the validated blueprint document before applying.' },
          { label: 'Create generated project', description: 'Saves the current project as a recovery point, replaces it with the compiled set, switches to Select mode, clears selection, and frames the new objects.' },
        ],
        notes: [
          'The current project is always snapshotted before a generated set is applied.',
          'Direct HTTP generation is optional via VITE_SET_GENERATION_ENDPOINT; credentials stay server-side.',
          'SetBlueprint is not a native project backup — use Open/Import Project Backup for LocationProject JSON.',
        ],
      },
      {
        id: 'build-selection',
        title: 'Selection and editing toolbar',
        summary: 'The floating selection tools operate on one object or the entire selected set.',
        controls: [
          { label: 'Selected object name', description: 'Renames a single selected object directly.' },
          { label: 'Precision drawer (I)', description: 'Opens exact numeric fields and object properties for one selected object.' },
          { label: 'Scene layers', description: 'Opens the scene hierarchy/list for selecting and managing objects.' },
          { label: 'Move (T)', description: 'Shows translation arrows. Multi-selection moves around the shared selection pivot.' },
          { label: 'Rotate (E)', description: 'Shows rotation rings. R and Shift+R rotate in 15-degree increments.' },
          { label: 'Scale (S)', description: 'Shows scale handles. [ and ] apply small scale steps.' },
          { label: 'Cut / Copy / Paste', description: 'Uses the system clipboard when available and an in-app fallback otherwise. Paste cascades copies; Ctrl/Cmd+Shift+V pastes in place.' },
          { label: 'Duplicate', description: 'Duplicates the current selection with D or Ctrl/Cmd+D.' },
          { label: 'Lock / Unlock', description: 'Locked objects cannot be transformed or deleted until unlocked.' },
          { label: 'Hide / Show', description: 'Toggles the selected objects. Alt+H reveals all hidden objects.' },
          { label: 'Delete', description: 'Deletes the unlocked selection after confirmation and creates a local recovery point first.' },
          { label: 'Undo / Redo', description: 'Reverses or reapplies Build edits. The header buttons mirror Ctrl/Cmd+Z and Ctrl/Cmd+Shift+Z.' },
          { label: 'Nudge', description: 'Arrow keys move on horizontal axes and Page Up/Down move vertically. Shift uses a coarse step; Alt uses a fine step.' },
        ],
      },
      {
        id: 'build-object-properties',
        title: 'Precision and object properties',
        summary: 'These fields define an object’s exact transform, export behavior, and graybox appearance.',
        controls: [
          { label: 'Name', description: 'The object label used in layers, staging, reports, and exported metadata.' },
          { label: 'Staging role', description: 'Set geometry is normally fixed, Movable prop is intended for per-shot staging, and Person / character participates in people and clean-plate controls.' },
          { label: 'Surface', description: 'Choose Default clay, Solid color, or the 1 m × 1 m checkerboard scale reference.' },
          { label: 'Color / Dark tile', description: 'Sets the solid color or the two checkerboard tile colors.' },
          { label: 'Position', description: 'Exact X, Y, and Z world coordinates.' },
          { label: 'Rotation', description: 'Exact X, Y, and Z Euler rotation values.' },
          { label: 'Dimensions', description: 'Exact width, height, and depth. Imported mesh bounds are represented in world-space dimensions.' },
        ],
      },
      {
        id: 'build-character-posing',
        title: 'Move Character versus Pose Character',
        summary: 'Person objects can be staged as rigid bodies or articulated with a shared human pose.',
        controls: [
          { label: 'Move Character', description: 'Places and orients the whole character with the normal Move / Rotate / Scale gizmos. Joint handles are hidden.' },
          { label: 'Pose Character', description: 'Opens skeletal posing. World transform stays separate from the saved humanPose.' },
          { label: 'Joint handles', description: 'Colored spheres on the mannequin select a joint. Handles keep a usable screen size when the character is scaled.' },
          { label: 'Joint list', description: 'Lists every semantic joint. Highlighted joints already have a non-neutral rotation.' },
          { label: 'Joint sliders', description: 'Euler X / Y / Z soft limits for the selected joint. A single slider drag records as one Undo step.' },
          { label: 'Presets', description: 'Applies built-in poses such as Sitting, Crouching, Walking contact, Reaching left/right, Pointing, and Looking directions.' },
          { label: 'Mirror pose', description: 'Mirrors left/right joints across the character’s sagittal plane. Mirror twice restores the original pose.' },
          { label: 'Reset pose / Reset joint', description: 'Clears every joint to neutral, or only the selected joint.' },
          { label: 'Pose persistence', description: 'humanPose saves with the project, including an explicit empty neutral pose. Duplicating a character copies its pose.' },
          { label: 'Poses in exports', description: 'Clay, projected, and depth stills and camera-move outputs render the posed skeleton. Shot staging and video keyframes can override pose per shot.' },
          { label: 'Save rig (.fsrig)', description: 'Downloads a ForeScene poseable-rig package for the selected autorigged character so it can be reused on matching meshes.' },
          { label: 'Import rig', description: 'Applies a .fsrig package (legacy .panorig also accepted) onto a compatible character without re-running the wizard.' },
        ],
        notes: [
          'Built-in characters use the bundled mannequin and the shared HumanJointId interface.',
          'Autorigged custom characters use Import poseable character, then the Joints → Pose & Fix wizard.',
        ],
      },
      {
        id: 'build-import',
        title: 'Import 3D scene',
        summary: 'Imports texture-free graybox geometry while preserving world-space layout.',
        controls: [
          { label: 'Choose files', description: 'Accepts GLB, embedded glTF, FBX, OBJ, STL, PLY, and .panoscene bundles. Blender, Maya, and Unreal project files must be exported first.' },
          { label: 'Keep objects separate', description: 'Creates selectable objects for source meshes or instanced-mesh groups. World transforms are baked and hierarchy is flattened.' },
          { label: 'Combine into one object', description: 'Combines all geometry into one asset and one scene object. Useful for very heavy scenes or a single collision/flow blocker.' },
          { label: 'Allow heavy imports', description: 'Permits imports above the normal performance recommendation after showing estimated memory, GPU, and storage cost.' },
          { label: 'Import report', description: 'Summarizes source size, object count, vertices, triangles, warnings, stripped materials/textures, and ignored animation or rigs.' },
          { label: 'Heavy / extreme confirmation', description: 'Requires explicit confirmation before importing geometry likely to stress browser memory or project storage.' },
          { label: 'Cancel import', description: 'Stops conversion while it is still cancellable.' },
        ],
        notes: [
          'Materials, textures, cameras, lights, animation, rigs, and morph targets are intentionally removed.',
          'External .bin sidecars are not loaded; use an embedded glTF or a single GLB.',
          'Ordinary Import 3D model or scene is for static graybox geometry only. Use Import poseable character for humanoids that will be posed.',
        ],
      },
      {
        id: 'build-poseable-import',
        title: 'Import poseable character',
        summary: 'A separate import path from graybox geometry. Establishes the poseable_rig asset lifecycle and the guided Joints → Pose & Fix wizard.',
        controls: [
          { label: 'Choose GLB / glTF / FBX', description: 'Loads one upright humanoid and previews its source meshes, deformation skeleton, mapping profile, materials, and textures when possible.' },
          { label: 'Front / Up', description: 'Declares which source axes should face the camera (+Z) and world up (+Y).' },
          { label: 'Ground (m)', description: 'Sets the ground contact height after orientation.' },
          { label: 'Approx. height (m)', description: 'Scales the character to an approximate real-world height.' },
          { label: 'Rest pose hint', description: 'Records whether the source is roughly an A-pose or T-pose for later marker suggestions.' },
          { label: 'Import character', description: 'Writes the unmodified source asset, a poseable_rig shell, and a Person scene object, then opens the rigging wizard.' },
          { label: 'Place joints', description: 'Move each dot to the matching joint. Front adjusts left/right and height; Side adjusts depth only.' },
          { label: 'Pose & Fix', description: 'Try example poses. Turn on Fix deformation to paint problem areas directly on the posed character, then Apply rig.' },
        ],
        notes: [
          'First version expects two arms, two legs, and one head with no extra limbs, tails, wings, or complex attached props.',
          'Use existing rig preserves source bones, skin indices, skin weights, inverse bind matrices, and multiple skinned meshes. Imported animation clips are recorded as metadata but are not played on the ForeScene timeline.',
          'The original source asset is retained so preserved-rig validation or autorigging can be retried without re-picking the file.',
          'Applying the rig stores markers, bind matrices, body-part labels, and skin weights for posing.',
          'Autorigged characters reload with the project. Missing or corrupt skin payloads fall back to an undeformed mesh instead of breaking the scene.',
        ],
      },
      {
        id: 'build-origin-rendering',
        title: 'Capture origin, appearance, and panorama output',
        summary: 'The capture origin is the physical position from which a panorama was or will be generated.',
        controls: [
          { label: 'Capture origin', description: 'Select Origin or press O, then use Move (T) and Rotate (E). Every panorama stores its own frozen origin.' },
          { label: 'Appearance: Clay / Projected / Depth', description: 'Clay shows graybox materials. Projected previews aligned styled panoramas when available. Depth shows linear camera-space depth (white = near by default).' },
          { label: 'Depth range / Invert', description: 'Auto or manual near/far meters for the depth preview. Invert switches to black = near. The same range is shared across a shot’s depth stills and motion.' },
          { label: 'Render 360 Reference', description: 'Renders a native 4096 × 2048 graybox equirectangular panorama for Reference and export.' },
          { label: 'Download Graybox 360', description: 'Downloads the latest rendered graybox panorama without rerendering.' },
          { label: 'Re-render after scene changes', description: 'Refreshes the graybox panorama after geometry or origin changes.' },
          { label: 'Download Projected 360', description: 'Renders an equirectangular seed from the current capture origin with projected textures. Use it for second-vantage inpainting and then import it in Reference.' },
        ],
        notes: [
          'Moving the capture origin never rewrites existing panorama origins.',
          'After moving the origin, projection may look mismatched until a second styled panorama is added and blended in Reference.',
        ],
      },
    ],
  },
  {
    id: 'reference',
    group: 'Workspaces',
    navLabel: 'Reference',
    title: 'Reference workspace',
    description: 'Import and align panoramas, manage multiple capture origins, place landmarks, and configure projected style.',
    workspace: 'reference',
    topics: [
      {
        id: 'reference-start',
        title: 'Starting or approving a reference',
        summary: 'A project needs either a styled panorama or an approved graybox before moving confidently into Shots.',
        defaultOpen: true,
        controls: [
          { label: 'Use Attached Reference', description: 'Loads the bundled sample/reference image when one is attached to the app build.' },
          { label: 'Import styled pano', description: 'Imports a photographed or AI-generated panorama using the current Build capture origin.' },
          { label: 'Use graybox only (skip styling)', description: 'Approves the graybox as the project reference when no styled image is needed.' },
          { label: 'Download Graybox 360', description: 'Downloads the Build graybox so it can be styled externally.' },
          { label: 'Approve as Reference / Looks good enough', description: 'Marks the active panorama as acceptable and advances workflow readiness.' },
          { label: 'Still misaligned — try again', description: 'Reopens retry guidance when yaw and opacity comparison cannot reconcile the image with the graybox.' },
        ],
      },
      {
        id: 'reference-viewer-alignment',
        title: 'Panorama viewer and Alignment panel',
        summary: 'Drag to look around and compare the styled panorama with the graybox beneath it.',
        controls: [
          { label: 'Drag to look around', description: 'Changes panorama yaw and pitch for inspection.' },
          { label: 'Yaw', description: 'Rotates the styled panorama left or right relative to the project. Reset returns to the prior/default yaw.' },
          { label: 'Graybox fade / compare opacity', description: 'Blends the graybox beneath the styled image so walls, openings, and landmarks can be compared.' },
          { label: 'Check pano alignment', description: 'Opens the guided alignment checklist.' },
          { label: 'Reopen alignment guide', description: 'Restarts the alignment guidance after it has been dismissed.' },
        ],
      },
      {
        id: 'reference-panoramas',
        title: 'Panoramas card and Reference Settings',
        summary: 'Manage every graybox, uploaded, and external panorama associated with the project.',
        controls: [
          { label: 'Panoramas', description: 'Selects the active panorama. Each entry shows its type, capture origin, and canonical/reference role.' },
          { label: 'Import', description: 'Adds a new styled panorama and stamps the current Build capture origin.' },
          { label: 'Fill missing areas…', description: 'Starts the second-vantage workflow for areas not well covered by the current panorama.' },
          { label: 'Settings', description: 'Opens Reference Settings, panorama management, projected-style controls, and advanced optimization.' },
          { label: 'Name', description: 'Shows the selected panorama name.' },
          { label: 'Download Active Pano', description: 'Downloads the selected panorama image.' },
          { label: 'Remove Uploaded Pano / Remove reference', description: 'Removes an uploaded or nonessential panorama after creating a recovery point.' },
          { label: 'Letterbox panorama exports to 16:9', description: 'Wraps 2:1 equirectangular panoramas into the project’s default shot width and height for compatible exports.' },
        ],
      },
      {
        id: 'reference-second-capture',
        title: 'Fill missing areas and second capture',
        summary: 'Use another origin when distant or occluded parts of the set do not project cleanly.',
        controls: [
          { label: 'Suggest a spot', description: 'Uses coverage analysis to recommend a complementary panorama origin.' },
          { label: 'Place in Build', description: 'Returns to Build so the capture origin can be positioned manually.' },
          { label: 'Add second capture', description: 'Imports a panorama from a different origin and keeps both origins for blending.' },
          { label: 'Replace same-origin reference', description: 'When the origin matches an existing reference, the import replaces that reference instead of creating a redundant second capture.' },
        ],
      },
      {
        id: 'reference-projected-style',
        title: 'Projected Style settings',
        summary: 'Controls how one or more styled panoramas are projected onto geometry in Build, Shots, and exports.',
        controls: [
          { label: 'Primary panorama', description: 'Choose a specific projector or leave Auto to use the canonical styled panorama.' },
          { label: 'Multi-origin blend', description: 'Choose primary only, secondary only, or a dominant-plus-fill blend when two styled captures are available.' },
          { label: 'Secondary panorama', description: 'Selects the second projector used outside primary-only mode.' },
          { label: 'Geometry occlusion', description: 'Prevents a panorama from projecting onto surfaces hidden behind other geometry from that origin.' },
          { label: 'Occlusion status', description: 'Shows whether occlusion data is disabled, generating, ready, failed, or falling back to legacy projection.' },
          { label: 'Ownership preview', description: 'Debug view: cyan is primary-owned, magenta secondary-owned, white a feathered seam, and red not visible to either projector.' },
          { label: 'Occlusion bias', description: 'Precision control that offsets the occlusion test to reduce false self-occlusion.' },
          { label: 'Edge softness', description: 'Precision control that softens visibility ownership around geometry edges.' },
          { label: 'Opacity', description: 'Overall projected-style opacity.' },
          { label: 'Exposure', description: 'Brightness multiplier from 0.25 to 4.0.' },
          { label: 'Lighting contribution', description: 'Blends scene lighting with the projected image.' },
          { label: 'Unsupported-area fallback', description: 'Choose Clay or Neutral for surfaces that no projector can cover.' },
        ],
      },
      {
        id: 'reference-coverage-optimizer',
        title: 'Coverage optimizer',
        summary: 'Analyzes geometry-visible surface coverage and proposes one or two complementary panorama origins.',
        controls: [
          { label: 'Search strategy', description: 'Keep current + find second preserves the current origin. Optimize both origins together searches a new pair.' },
          { label: 'Restrict optimizer to an analysis region', description: 'Limits candidate placement and scored surfaces to a defined world-space volume.' },
          { label: 'Use selection bounds', description: 'Uses selected Build objects to fill the region bounds.' },
          { label: 'X/Y/Z minimum and maximum', description: 'Defines the analysis volume numerically. Minimum must not exceed maximum.' },
          { label: 'Analyze panorama origins', description: 'Builds indexed scene geometry, samples candidates, and reports usable A/B coverage, overlap, combined coverage, reachable upper bound, and estimated remainder.' },
          { label: 'Move capture origin to A / B', description: 'Applies a recommended origin to the current Build capture origin without rewriting existing panoramas.' },
        ],
      },
      {
        id: 'reference-landmarks',
        title: 'Landmarks',
        summary: 'Landmarks identify continuity-critical points and remain associated with the correct panorama origin.',
        controls: [
          { label: 'Landmark markers', description: 'Click visible markers in the viewer to focus them and turn toward their stored yaw/pitch.' },
          { label: 'Landmark list', description: 'Selects, renames, shows, hides, and manages continuity landmarks.' },
          { label: 'Shot landmark assignment', description: 'In Shots, choose which project landmarks are important for a specific shot and prompt.' },
        ],
      },
    ],
  },
  {
    id: 'shots',
    group: 'Workspaces',
    navLabel: 'Shots',
    title: 'Shots workspace',
    description: 'Compose stills, author camera moves, stage objects, compare continuity, and manage the shot sequence.',
    workspace: 'shots',
    topics: [
      {
        id: 'shots-viewfinder',
        title: 'Viewfinder basics',
        summary: 'Shots behaves like a live production camera inside the graybox.',
        defaultOpen: true,
        controls: [
          { label: 'Still / Video', description: 'Switches between a single captured camera and a multi-keyframe camera move.' },
          { label: 'Clay / Projected / Depth', description: 'Changes the viewfinder appearance. The setting is a view mode; configured exports may include clay, projected, and depth variants.' },
          { label: 'Hide people / Show people', description: 'Temporarily hides or reveals objects classified as people in the viewfinder, including depth appearance.' },
          { label: 'Fly camera', description: 'Use WASD and mouse-look to compose. The camera remains live after a still capture so you can continue to the next shot.' },
          { label: 'Height and FOV', description: 'Quick viewfinder controls for camera elevation and vertical field of view.' },
          { label: 'Open shot library', description: 'Opens the previous-shots overlay for review and shot management.' },
          { label: 'Camera settings / Settings (I)', description: 'Opens complete shot, lens, clipping, staging, sequence, and export settings.' },
        ],
      },
      {
        id: 'shots-still',
        title: 'Still capture',
        summary: 'Capture creates a persisted shot preview while leaving the viewfinder live.',
        controls: [
          { label: 'Capture', description: 'Saves the current camera as a still shot and generates the configured clay/projected companion media.' },
          { label: 'Add shot / New shot', description: 'Creates another shot camera without overwriting the current shot.' },
          { label: 'Refresh thumbnail', description: 'Regenerates the library thumbnail from the current shot state.' },
          { label: 'Next shot', description: 'Moves to or creates the next composition while preserving the current result.' },
        ],
        notes: ['Stills default to the project shot resolution, commonly 3840 × 2160.'],
      },
      {
        id: 'shots-video',
        title: 'Sequential video capture',
        summary: 'Author a camera move by capturing poses in order; the state machine keeps the camera path, thumbnails, and staged-object snapshots synchronized.',
        controls: [
          { label: 'Capture start', description: 'Stores the first camera pose and the starting object-override snapshot.' },
          { label: 'Capture next', description: 'Adds the current camera and staged-object pose as the next keyframe.' },
          { label: 'Finish capture', description: 'Completes a move after at least two poses.' },
          { label: 'Continue sequence', description: 'Reopens a finished move so another keyframe can be appended.' },
          { label: 'Retake move', description: 'Clears the current move and returns to the initial capture state.' },
          { label: 'Next shot', description: 'Saves the finished move and begins the next shot. Direct MP4 export is optional.' },
          { label: 'Video duration / Length', description: 'Sets total move duration using quick picks while recording.' },
          { label: 'Start set / Pose captured / Move complete', description: 'Status indicators explaining the next expected capture action.' },
        ],
      },
      {
        id: 'shots-staging',
        title: 'Per-shot staging and object animation',
        summary: 'Shot overrides move, rotate, pose, show, or hide objects without changing the base Build set.',
        controls: [
          { label: 'Stage / Per-shot staging', description: 'Opens the staging panel. Select an object in the viewfinder or list.' },
          { label: 'People & props', description: 'Default Stage list scope: people and movable props only, so large imported sets stay responsive.' },
          { label: 'All objects', description: 'Expands the Stage list to every stageable object when you need set geometry.' },
          { label: 'Search staged objects…', description: 'Filters the Stage list by object name.' },
          { label: 'Move', description: 'Changes the selected object’s shot-specific position.' },
          { label: 'Rotate', description: 'Changes the selected object’s shot-specific rotation.' },
          { label: 'Pose', description: 'For poseable characters: hides the transform gizmo, enables joint handles, and opens the pose panel. Edits write to this shot’s (or selected keyframe’s) humanPose override only.' },
          { label: 'Hide in shot / Show in shot', description: 'Overrides visibility for this shot only.' },
          { label: 'Reset pose to set', description: 'Clears only the pose override so the character returns to its Build pose while keeping position, rotation, and visibility staging.' },
          { label: 'Reset all staging to set', description: 'Removes the entire shot override—position, rotation, visibility, and pose—and returns the object to its Build state.' },
          { label: 'Copy staging → next', description: 'Copies the current shot’s object overrides—including character poses—to the following shot.' },
          { label: 'Video object snapshots', description: 'Every video keyframe stores stageable-object overrides, including humanPose for posed characters, so props or characters can animate with the camera path. With a keyframe selected, Stage pose edits go into that keyframe’s inspection map until Recapture keyframe commits them.' },
        ],
      },
      {
        id: 'shots-identity-status',
        title: 'Shot identity, status, notes, and people output',
        summary: 'These fields make the shot usable in a production sequence and control clean-plate delivery.',
        controls: [
          { label: 'Production shot ID', description: 'Optional code such as 42A. It is used in display and export naming when present.' },
          { label: 'Title', description: 'Human-readable shot name.' },
          { label: 'Status', description: 'Choose New, Planned, Exported, Needs fix, Approved, or Rejected.' },
          { label: 'Description', description: 'Shot-specific creative, editorial, or continuity notes.' },
          { label: 'People export', description: 'Choose With people, Clean plate, or Both. Clean plate keeps camera and staging but hides every Person / character object.' },
        ],
      },
      {
        id: 'shots-camera-settings',
        title: 'Camera, lens, clipping, and resolution',
        summary: 'Exact camera values are editable and exported as metadata.',
        controls: [
          { label: 'Camera Position', description: 'Exact X, Y, and Z camera position.' },
          { label: 'Camera Target / Look-at target', description: 'Exact point the camera looks toward.' },
          { label: 'Vertical FOV', description: 'The camera’s vertical field of view.' },
          { label: 'Focal length', description: 'Lens-style control synchronized with FOV and aspect ratio.' },
          { label: 'Aspect ratio', description: 'Relationship between shot width and height.' },
          { label: 'Near Clip', description: 'Hides geometry closer than this distance to the camera.' },
          { label: 'Far Clip', description: 'Stops drawing geometry beyond this distance.' },
          { label: 'Resolution / Width / Height', description: 'Pixel dimensions for still renders and package outputs.' },
        ],
      },
      {
        id: 'shots-continuity-tools',
        title: 'Continuity, sequence, pano match, and landmarks',
        summary: 'Compare the current shot with neighboring cameras and the linked panorama.',
        controls: [
          { label: 'Shot-to-shot continuity', description: 'Shows deltas between the active shot and the previous shot, including camera, lens, clipping, staging, and visibility changes.' },
          { label: 'Previous shot overlay', description: 'Displays the previous composition as an overlay for visual matching.' },
          { label: 'Sequence storyboard', description: 'Shows shot order, thumbnails, still/video type, duration, and total sequence length.' },
          { label: 'Play animatic / Stop animatic', description: 'Plays the sequence using shot durations and the playhead.' },
          { label: 'Pano match', description: 'Previews the perspective crop from the linked panorama using the locked camera angle and Reference yaw.' },
          { label: 'Open in 360', description: 'Opens the linked panorama for broader inspection.' },
          { label: 'Landmarks', description: 'Assigns project landmarks to the active shot for continuity and prompt context.' },
        ],
      },
      {
        id: 'shots-timeline',
        title: 'Timeline, keyframe editor, and preview',
        summary: 'Fine-tune a recorded camera move after sequential capture.',
        controls: [
          { label: 'Edit timeline', description: 'Opens the timeline explicitly. It also appears automatically for longer moves.' },
          { label: 'Keyframe stills', description: 'Shows generated previews for each captured pose.' },
          { label: 'Play path / Preview move', description: 'Plays camera and staged-object interpolation live in the viewfinder.' },
          { label: 'Stop preview', description: 'Stops playback and restores normal authoring controls.' },
          { label: 'Recapture keyframe', description: 'Replaces a selected keyframe with the current camera and staged-object state.' },
          { label: 'Time seconds', description: 'Sets the selected keyframe time.' },
          { label: 'Insert here', description: 'Adds a keyframe at the current playhead or camera pose.' },
          { label: 'Delete keyframe', description: 'Removes the selected pose while preserving valid move ordering.' },
          { label: 'Motion easing', description: 'Applies the selected timing curve between every keyframe.' },
          { label: 'Set Start / Set End', description: 'Manual fallback controls. Sequential Capture start / Capture next is the preferred authoring path.' },
        ],
      },
      {
        id: 'shots-library-media',
        title: 'Shot library and media viewer',
        summary: 'Review saved media and manage each shot without leaving the workspace.',
        controls: [
          { label: 'Shot thumbnail', description: 'Opens the media viewer. Badges indicate captures, multiple media variants, or camera moves.' },
          { label: 'Rename', description: 'Edits Production ID and Shot title, then Save or Cancel.' },
          { label: 'Open shot', description: 'Makes the library card the active shot.' },
          { label: 'Duplicate', description: 'Creates a new shot copied from the selected shot.' },
          { label: 'Delete shot', description: 'Removes the shot and its saved captures after confirmation. The only remaining shot cannot be deleted.' },
          { label: 'Previous shot / Next shot', description: 'Navigates between media in sequence order.' },
          { label: 'Projection', description: 'Choose Clay or Projected media when both exist.' },
          { label: 'People', description: 'Choose People or Clean plate media when both exist.' },
          { label: 'Keyframes / Play animation', description: 'Reviews keyframe stills or animates a saved move.' },
          { label: 'Download', description: 'Downloads the currently viewed still or media variant.' },
        ],
      },
      {
        id: 'shots-video-export',
        title: 'Video advanced settings and MP4 export',
        summary: 'Configure direct video encoding separately from the final package settings.',
        controls: [
          { label: 'Duration Seconds', description: 'Exact total move duration. Quick duration picks are also available while recording.' },
          { label: 'Export mode', description: 'Render MP4 uses fixed-step H.264 intended for Resolve. Quick Preview records in real time and may drop frames.' },
          { label: 'Video resolution', description: 'Sets direct video dimensions. Package export uses the project Video performance profile (Fast Control 720p24, Standard 1080p30, High Quality 4K30); stills retain shot resolution.' },
          { label: 'Export MP4', description: 'Encodes and downloads the active camera move. Render MP4 requires a current Chromium browser with WebCodecs.' },
          { label: 'Cancel MP4', description: 'Stops the export at a supported cancellation point.' },
        ],
      },
    ],
  },
  {
    id: 'export',
    group: 'Workspaces',
    navLabel: 'Export',
    title: 'Export workspace',
    description: 'Configure Scene Export Settings once, override exceptional shots, resolve readiness checks, and download a structured continuity package.',
    workspace: 'export',
    topics: [
      {
        id: 'export-selection',
        title: 'Shot selection and readiness',
        summary: 'Choose one or more shots, then review warnings before building the package.',
        defaultOpen: true,
        controls: [
          { label: 'Select Shots to Export', description: 'Checks the shots included in the multi-shot ZIP. Checkbox selection is independent from which shot you are customizing in Export Settings.' },
          { label: 'Using scene settings / shot overrides', description: 'Each shot row shows whether it inherits Scene Export Settings or has sparse shot overrides.' },
          { label: 'Package readiness', description: 'Reports Ready, Ready with notes, blocking checks, or Needs attention.' },
          { label: 'Checks and notes', description: 'Warns about missing graybox/projectors/panoramas, unavailable projected outputs, missing landmarks, or an aspect-ratio mismatch.' },
        ],
      },
      {
        id: 'export-settings',
        title: 'Scene Export Settings and shot overrides',
        summary: 'Configure the scene once. Customize a shot only when it needs different deliverables.',
        controls: [
          { label: 'Scene Export Settings', description: 'Defaults inherited by every shot that does not override a field.' },
          { label: 'Customize this shot', description: 'Sparse overrides for the active shot. Unchanged fields keep using scene settings.' },
          { label: 'Reset to scene settings', description: 'Clears one field or all overrides so the shot inherits again.' },
          { label: 'Copy overrides', description: 'Replaces overrides on checked shots with the active shot’s override set.' },
          { label: 'Promote to scene settings', description: 'Makes the active shot’s resolved settings the new scene defaults without changing other shots’ resolved output.' },
          { label: 'Width / Height', description: 'Final output pixel dimensions. In shot mode, choose Use scene setting or a custom value.' },
          { label: 'People output', description: 'Choose With people, Clean plate, or Both.' },
          { label: 'Characters-only pass', description: 'Optional transparent stills, green-screen MP4, and/or transparent PNG sequence with character-linked props.' },
          { label: 'Clay control frame', description: 'Includes the shot rendered with graybox materials.' },
          { label: 'Projected reference', description: 'Includes projected style and a clay companion when available.' },
          { label: 'AI result frame', description: 'Includes an already attached AI/final frame; it does not generate a new image.' },
          { label: 'Pano crop', description: 'Includes the perspective crop matching the shot camera and linked panorama.' },
          { label: 'Canonical / styled panorama', description: 'Includes the full equirectangular canonical/styled panorama as global_reference.png.' },
          { label: 'Cubemap faces', description: 'Optional six-face + stitched cubemap from the styled or linked panorama. Off by default; enable only when a downstream tool needs undistorted environment faces.' },
          { label: 'Graybox panorama', description: 'Includes the rendered graybox 360 from Build.' },
          { label: 'Camera-motion clay / projected video', description: 'Encodes the move using clay or projected appearance.' },
          { label: 'Camera reference frames', description: 'Includes individual clay or projected reference frames for the move.' },
          { label: 'Depth reference (linear camera depth)', description: 'Enables depth deliverables. Depth is a grayscale metric reference, not a look to copy into AI generation.' },
          { label: 'Metadata JSON', description: 'Includes camera transforms, lens/clipping data, staging, keyframes, shot identity, and other machine-readable metadata.' },
          { label: 'Prompts', description: 'Includes image/video prompt material and notes. A note appears when no continuity landmarks are pinned.' },
          { label: 'ZIP layout', description: 'Scene-wide choice between Legacy v1 (current per-shot inputs/ layout) and ForeScene v2 (pilot: shared_references/ + shots/ layout with a START_HERE.html landing page). Existing projects keep Legacy v1 until you opt in.' },
          { label: 'Export Final ZIP (current shot)', description: 'Builds a package for only the active shot.' },
          { label: 'Add Camera', description: 'Creates another camera/shot without navigating to Shots, useful when configuring exports from an empty or incomplete sequence.' },
        ],
        notes: [
          'Depth silhouettes should match clay geometry for the same camera. Clean-plate people output omits Person / character objects from depth as well as clay/projected.',
          'Posed characters appear in clay, projected, and depth stills and motion when people are included.',
        ],
      },
      {
        id: 'export-package',
        title: 'Multi-shot ZIP and manifest',
        summary: 'A batch export produces one ZIP with a folder for every selected shot.',
        controls: [
          { label: 'Export Selected Shots', description: 'Builds the selected shots into a single ZIP, avoiding browser multi-download blocking.' },
          { label: 'Package Contents', description: 'Summarizes reference/camera data, final frames/media, shot/scene info, prompts/notes, and the package manifest.' },
          { label: 'Active shot manifest sample', description: 'Lists expected paths for the active shot before export. The checked batch may include additional shots.' },
          { label: 'Last Export', description: 'Shows the latest completed package result for this session.' },
          { label: 'Package manifest', description: 'Describes every included file and its role so agents and pipeline tools can consume the handoff reliably.' },
        ],
      },
      {
        id: 'export-progress',
        title: 'Progress, cancellation, and failures',
        summary: 'Exports run locally and may include multiple rendering, encoding, and compression stages.',
        controls: [
          { label: 'Progress panel', description: 'Shows current shot, stage, message, and percentage or indeterminate activity.' },
          { label: 'Cancel export', description: 'Requests cancellation between major steps. A currently running render or ZIP pass may complete first.' },
          { label: 'Dismiss progress', description: 'Closes the completed, failed, or cancelled progress panel.' },
          { label: 'Blocking errors', description: 'Prevent export when required inputs are missing.' },
          { label: 'Nonblocking notes', description: 'Allow export while explaining which optional outputs will be omitted.' },
        ],
      },
    ],
  },
  {
    id: 'pano-viewer',
    group: 'Workspaces',
    navLabel: '360 viewer',
    title: 'Standalone 360 panorama viewer',
    description: 'Inspect an equirectangular image and download the current perspective without modifying the continuity project.',
    mode: 'panoViewer',
    topics: [
      {
        id: 'viewer-controls',
        title: 'Viewer controls',
        summary: 'A deliberately small utility mode for panorama inspection.',
        defaultOpen: true,
        controls: [
          { label: 'Import pano', description: 'Loads an equirectangular image into the viewer.' },
          { label: 'Replace pano', description: 'Replaces the currently loaded viewer image.' },
          { label: 'Drag to look', description: 'Changes the current yaw and pitch.' },
          { label: 'FOV / Field of view', description: 'Changes the perspective zoom.' },
          { label: 'Download current view', description: 'Renders the current perspective as a flat PNG.' },
          { label: 'Open ForeScene', description: 'Returns to the full production workflow through the brand menu.' },
        ],
      },
    ],
  },
  {
    id: 'project-files',
    group: 'Project & guidance',
    navLabel: 'Projects & backups',
    title: 'Projects, backups, and imported media',
    description: 'Understand what is editable, what is a deliverable, and how browser-local media is handled.',
    topics: [
      {
        id: 'project-backups',
        title: 'Editable project backups',
        summary: 'Backups preserve the project document and referenced local binary media.',
        defaultOpen: true,
        controls: [
          { label: 'Import Project Backup', description: 'Validates and opens .fsp backups, plus legacy .forescene-project, .panoref-project, .zip, or .json files.' },
          { label: 'Export Project Backup', description: 'Downloads a verified editable backup as project_name_forescene.fsp (always a ZIP containing project.json and any binary media).' },
          { label: 'Legacy backups', description: 'Older .panoref-project and transitional .forescene-project packages remain importable indefinitely.' },
          { label: 'New Project confirmation', description: 'Explains that the current project is replaced in the editor while remaining available through local recovery.' },
          { label: 'Project import status', description: 'Reports success, validation errors, blocked writes, or recovery-related restrictions.' },
        ],
      },
      {
        id: 'interchange-formats',
        title: 'Interchange formats and legacy compatibility',
        summary: 'New exports use ForeScene names; older PanoRef / Continuity Stage identifiers remain readable.',
        controls: [
          { label: 'Project backup', description: 'New: .fsp (ZIP). Legacy import: .forescene-project, .panoref-project, .zip, .json.' },
          { label: 'Poseable rig package', description: 'New: .fsrig with forescene-poseable-rig v2. Legacy import: .panorig with panoref-poseable-rig v1.' },
          { label: 'Scene bundle', description: 'Extension stays .panoscene. Manifest may be forescene-scene.json or legacy panoref-scene.json.' },
          { label: 'Local browser storage', description: 'IndexedDB database names and asset URI prefixes keep historical panoref-* identifiers so existing projects and recovery history keep opening.' },
        ],
      },
      {
        id: 'project-vs-package',
        title: 'Project backup versus handoff package',
        summary: 'The two downloads serve different purposes.',
        controls: [
          { label: 'Project backup', description: 'Use for reopening and editing the project.' },
          { label: 'Continuity ZIP package', description: 'Use for AI generation, review, compositing, and downstream pipeline handoff.' },
          { label: 'Local media', description: 'Imported models, panoramas, captures, and generated motion are stored in browser databases and referenced by the project.' },
        ],
      },
    ],
  },
  {
    id: 'safety-recovery',
    group: 'Project & guidance',
    navLabel: 'Safety & recovery',
    title: 'Project Safety & Recovery',
    description: 'Inspect verified revisions, browser storage, retained histories, integrity issues, and safe repairs.',
    topics: [
      {
        id: 'recovery-points',
        title: 'Recovery points',
        summary: 'Every verified save retains the current version and previous known-good revision; additional snapshots and milestones provide longer history.',
        defaultOpen: true,
        controls: [
          { label: 'Snapshot reason', description: 'Optional label describing why a manual recovery point is being created.' },
          { label: 'Snapshot', description: 'Creates a manual recovery point.' },
          { label: 'Recovery point filters', description: 'Filter Milestones, Automatic recovery, Autosaves, All revisions, or points created Before a destructive action.' },
          { label: 'Restore', description: 'Restores the selected verified revision while retaining the current revision for rollback.' },
          { label: 'Current verified revision / Previous known-good', description: 'Badges identify the active durable head and its rollback partner.' },
        ],
      },
      {
        id: 'storage-panel',
        title: 'Storage panel',
        summary: 'Shows how much of the project is essential, temporary, or retained for recovery.',
        controls: [
          { label: 'Project', description: 'Logical project-document size.' },
          { label: 'Essential local', description: 'Local binary data required by the active project.' },
          { label: 'Temporary local', description: 'Unreferenced or cleanup-eligible local data.' },
          { label: 'Browser used / Browser remaining', description: 'Storage-estimate values reported by the browser.' },
          { label: 'Revisions / Snapshots', description: 'Counts retained recovery records.' },
          { label: 'Last verified save', description: 'Timestamp for the latest durable revision.' },
          { label: 'Persistent storage', description: 'Shows whether the browser granted protection against storage eviction.' },
          { label: 'Export backup', description: 'Downloads a portable copy before cleanup or storage pressure becomes critical.' },
          { label: 'Free temporary data', description: 'Removes unreferenced binary data not needed by any retained revision.' },
          { label: 'Largest assets', description: 'Lists the largest local media items to help diagnose storage use.' },
        ],
      },
      {
        id: 'local-histories-health',
        title: 'Local histories and Project Health',
        summary: 'Manage older projects retained in this browser and scan the active project for integrity problems.',
        controls: [
          { label: 'Open local history', description: 'Deliberately opens an older locally retained project.' },
          { label: 'Remove local history', description: 'Deletes an unwanted project history and reclaims media no other retained project references.' },
          { label: 'Scan again', description: 'Checks asset references, missing binary payloads, duplicate IDs, cameras, keyframes, pano links, legacy data, and storage pressure.' },
          { label: 'Repair safe issues', description: 'Applies repairs classified as safe, such as pruning or normalizing recoverable metadata.' },
          { label: 'Issue severity and repair badge', description: 'Explains whether an issue is informational, a warning, an error, and whether automatic safe repair is available.' },
        ],
      },
    ],
  },
  {
    id: 'guidance',
    group: 'Project & guidance',
    navLabel: 'Objectives & guidance',
    title: 'Current Objective and guided workflows',
    description: 'Contextual help that explains what to do next while leaving the app fully navigable.',
    topics: [
      {
        id: 'objective-controls',
        title: 'Current Objective',
        summary: 'The objective card changes with Build, Reference, Shots, and Export readiness.',
        controls: [
          { label: 'Show current objective', description: 'Opens the objective for the current workspace.' },
          { label: 'Got it / Not right now / Close', description: 'Dismisses guidance without changing project data.' },
          { label: 'Ready for the next step / Continue', description: 'Acknowledges the current stage and moves to the suggested next action.' },
          { label: 'Start checking', description: 'Begins the Reference alignment checklist.' },
          { label: 'Try generating again', description: 'Shows practical retry guidance when the styled pano cannot be aligned by yaw.' },
        ],
      },
      {
        id: 'image-ai-handoff',
        title: 'Graybox-to-image-AI handoff',
        summary: 'The Build objective prepares the files and prompt used to generate a styled panorama externally.',
        controls: [
          { label: 'Your scene idea', description: 'Describe style, time of day, materials, mood, and other visual direction.' },
          { label: 'Prompt for your image AI', description: 'Generated instruction block to paste into an image model along with the graybox.' },
          { label: 'Copy prompt', description: 'Copies the complete prompt.' },
          { label: 'Download 16:9 graybox / graybox PNG', description: 'Downloads the relevant graybox image for the external model.' },
          { label: 'Import the finished panorama', description: 'Returns the styled result to Reference for alignment and approval.' },
        ],
      },
    ],
  },
  {
    id: 'shortcuts',
    group: 'Reference',
    navLabel: 'Keyboard shortcuts',
    title: 'Keyboard shortcuts',
    description: 'Fast controls for Build editing, camera movement, media review, and common dialogs.',
    topics: [
      {
        id: 'build-shortcuts',
        title: 'Build editing shortcuts',
        summary: 'The most important editing keys are also shown from the Build help shortcut.',
        defaultOpen: true,
        controls: [
          { label: 'Ctrl/Cmd+C · X · V', description: 'Copy, cut, and cascading paste.' },
          { label: 'Ctrl/Cmd+Shift+V', description: 'Paste in place at original world coordinates.' },
          { label: 'Ctrl/Cmd+A · Shift+A · Escape', description: 'Select all, deselect all, or clear/return to Select.' },
          { label: 'D · Ctrl/Cmd+D', description: 'Duplicate selection.' },
          { label: 'T · E · S', description: 'Move, rotate, and scale gizmos.' },
          { label: 'R · Shift+R · [ · ]', description: 'Rotate right/left and scale down/up in fixed steps.' },
          { label: 'Arrow keys · Page Up/Down', description: 'Nudge along world axes; Shift is coarse and Alt is fine.' },
          { label: 'F · Home', description: 'Frame selection or all visible objects.' },
          { label: 'H · Alt+H · L', description: 'Hide selection, show all, and lock/unlock.' },
          { label: 'Ctrl/Cmd+Z · Ctrl/Cmd+Shift+Z', description: 'Undo and redo.' },
          { label: 'O · G · I · F2 · ?', description: 'Origin, snap, precision drawer, rename, and help.' },
          { label: '1–9 / 0', description: 'Choose primitive placement tools.' },
        ],
      },
      {
        id: 'navigation-shortcuts',
        title: 'Camera, preview, and dialog shortcuts',
        summary: 'Common movement and dismissal keys used outside direct Build editing.',
        controls: [
          { label: 'WASD', description: 'Moves the free camera in Build and Shots.' },
          { label: 'Space / Shift', description: 'Moves the Build free camera up/down.' },
          { label: 'Double-tap W', description: 'Sprints in Build free-camera mode.' },
          { label: 'Escape', description: 'Exits free camera, stops/backs out of many preview states, closes menus, or cancels inline editing.' },
          { label: 'Arrow Left / Arrow Right', description: 'Moves among camera-move keyframes or media where supported.' },
          { label: 'Enter', description: 'Confirms selected inline actions and may dismiss the intro.' },
        ],
      },
    ],
  },
  {
    id: 'limits',
    group: 'Reference',
    navLabel: 'Limits & compatibility',
    title: 'Limits, browser compatibility, and performance',
    description: 'Important boundaries that affect imports, storage, projection, rendering, and video encoding.',
    topics: [
      {
        id: 'compatibility',
        title: 'Browser and media compatibility',
        summary: 'Most functionality is browser-independent; some video and GPU paths require specific support.',
        controls: [
          { label: 'Render MP4', description: 'Requires a current Chromium browser with WebCodecs. Chrome and Edge are the recommended targets.' },
          { label: 'Quick Preview', description: 'Uses real-time browser recording when available and may drop frames.' },
          { label: 'WebKit', description: 'Stable smoke paths are supported, while some Linux software-WebKit GPU workflows are treated as a nonblocking canary.' },
          { label: 'Clipboard', description: 'Falls back to an in-app clipboard if system clipboard access is blocked.' },
        ],
      },
      {
        id: 'performance-storage',
        title: 'Performance and storage behavior',
        summary: 'All rendering, encoding, compression, and persistence happen locally.',
        controls: [
          { label: 'Heavy imports', description: 'Large source files, high triangle counts, or many separate objects can increase conversion time, RAM/GPU use, save/load time, and crash risk.' },
          { label: 'Geometry is not simplified', description: 'Imported geometry is preserved; the importer warns or blocks instead of silently reducing it.' },
          { label: '360 and cubemap renders', description: 'High-resolution equirectangular and cubemap work may take time because it is generated in the browser.' },
          { label: 'Storage pressure warnings', description: 'Project Safety warns when browser storage is nearly full or persistent storage was not granted.' },
          { label: 'Performance budgets', description: 'Documented values are measured baselines and recommendations unless explicitly identified as hard safety limits.' },
          { label: 'Agent artifact registry', description: 'Keeps at most 64 artifacts or 512 MiB. Published, persisted, project-attached, and in-flight handles stay pinned. Unpublished outputs from a paused or cancelled job generation are deleted after that generation drains so they cannot pin memory forever.' },
        ],
      },
      {
        id: 'character-limits',
        title: 'Poseable character limits',
        summary: 'Built-in mannequins and future autorigged imports share one HumanJointId interface, with different fidelity limits.',
        controls: [
          { label: 'Built-in Person', description: 'Uses the bundled adult mannequin. Posing is semantic (joints, presets, mirror) rather than full animation or IK targeting.' },
          { label: 'Ordinary model import', description: 'Import 3D model or scene strips materials, textures, animation, and rigs. It cannot produce a poseable character.' },
          { label: 'Autorigged import', description: 'Import → Poseable character accepts upright A/T-pose humanoids, fits a skeleton from placed markers, and generates skin weights so the character can be posed. Extra limbs, tails, wings, and complex attached props remain out of scope for the first version.' },
          { label: 'Skinning fidelity', description: 'Autorig weights are geometric approximations for blocking and continuity, not production character animation quality.' },
        ],
      },
    ],
  },
  {
    id: 'troubleshooting',
    group: 'Reference',
    navLabel: 'Troubleshooting',
    title: 'Troubleshooting',
    description: 'Common symptoms, likely causes, and the first corrective action to try.',
    topics: [
      {
        id: 'troubleshooting-common',
        title: 'Common problems',
        summary: 'Start here before changing project data or retrying a costly render.',
        defaultOpen: true,
        controls: [
          { label: 'Panorama looks stretched', description: 'Use a true 2:1 equirectangular image. Letterboxed 16:9 inputs may be detected and extracted, but arbitrary aspect ratios will distort in a 360 viewer.' },
          { label: 'Styled pano does not align', description: 'Lower Graybox fade and adjust yaw. If scene structure still differs, regenerate the panorama rather than forcing alignment.' },
          { label: 'Projected areas look thin or wrong', description: 'Check the panorama origin, projected-style ownership preview, geometry occlusion, and whether a second capture is needed.' },
          { label: 'Build object will not move', description: 'Check whether any selected object is locked and confirm that Select/Move mode—not Origin—is active.' },
          { label: 'Translate gizmo seems detached', description: 'Exit free camera or object focus, reselect the object, and confirm the current transform tool is Move.' },
          { label: 'Clipboard paste does nothing', description: 'Keep the app focused. If browser clipboard access is blocked, copy again so the in-app clipboard is populated.' },
          { label: 'Import fails', description: 'Use a supported geometry-only format, embed glTF buffers, remove compression extensions, or export a single GLB.' },
          { label: 'MP4 export is unavailable', description: 'Use current Chrome or Edge and capture at least two camera poses.' },
          { label: 'Export takes a long time', description: 'Disable unneeded panoramas, cubemaps, projected outputs, motion variants, or reference frames; shorten the move if appropriate.' },
          { label: 'Local save failed', description: 'Open Project Safety, export a backup, inspect storage pressure, and preserve the previous verified revision before cleanup.' },
          { label: 'Missing media after restart', description: 'Run Project Health. Session-only blob URLs or missing local asset keys indicate media that was never durably persisted.' },
          { label: 'A feature appears disabled', description: 'Read the nearby readiness message. Most disabled actions explain a missing selection, panorama, capture, verified save, browser capability, or required prior stage.' },
        ],
      },
    ],
  },
];

export function helpCatalogText(): string {
  return helpSections
    .flatMap((section) => [
      section.navLabel,
      section.title,
      section.description,
      ...section.topics.flatMap((topic) => [
        topic.title,
        topic.summary,
        ...(topic.notes ?? []),
        ...topic.controls.flatMap((control) => [
          control.label,
          control.description,
          ...(control.details ?? []),
          ...(control.keywords ?? []),
        ]),
      ]),
    ])
    .join('\n');
}
